name: Shell commands

on: [push]

jobs: 
  run-github-actions:
    runs-on: ubuntu-latest
    steps: 
      - name: simple js actions
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: "Mikhail"
      - name: log greeting time
        run: echo "time is ${{ steps.greet.outputs.time }}"
      - name: list files in the repo
        run: |
          pwd
          ls -al
      - name: checkout master
        uses: actions/checkout@v2
      -name: list files in the repo
        run: |
          pwd
          ls -al